### ISSUE TITLE
Fedora 41

### ISSUE THREAD

**Issue by jsf9k** [geerlingguy/docker-fedora40-ansible#4]
Hi @geerlingguy!  Thank you for providing these Docker images.  Do you plan to create a Fedora 41 image soon?  [Fedora 41 was released](https://www.redhat.com/en/blog/announcing-fedora-41) on October 29th of this year.

Thank you,
@jsf9k

**Comment by geerlingguy** [comment]
Done! Building now for https://hub.docker.com/repository/docker/geerlingguy/docker-fedora41-ansible/general

**Comment by jsf9k** [comment]
> Done! Building now for https://hub.docker.com/repository/docker/geerlingguy/docker-fedora41-ansible/general

Thank you for the extremely fast response!
